version: '3.9'

services:
  mariadb:
    container_name: mariadb
    networks:
      - network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: true
      - path: ../secrets/credentials.txt
        required: false
      - path: ../secrets/db_password.txt
        required: false
      - path: ../secrets/db_root_password.txt
        required: false
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - network
    depends_on:
      - wordpress
      - mariadb
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
      - path: ./.env
        required: true
      - path: ../secrets/credentials.txt
        required: false
      - path: ../secrets/db_password.txt
        required: false
      - path: ../secrets/db_root_password.txt
        required: false
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file:
      - path: ./.env
        required: true
      - path: ../secrets/credentials.txt
        required: false
      - path: ../secrets/db_password.txt
        required: false
      - path: ../secrets/db_root_password.txt
        required: false
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - network
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'

networks:
  network:
    name: inception
    driver: bridge
